WITH TBL AS (
    SELECT 
        ANNO, MES, ID_EMPRESA,DESC_EMPRESA,ID_ELEMENTO,ELEMENTO_PACTADO, ID_TECNOLOGIA,
		CASE 
            WHEN ID_TECNOLOGIA = 1  THEN '2G'
            WHEN ID_TECNOLOGIA = 2  THEN '3G'
			WHEN ID_TECNOLOGIA = 3  THEN '4G'
            WHEN ID_TECNOLOGIA = 4  THEN 'CMTS'
			WHEN ID_TECNOLOGIA = 5  THEN 'OLT'
            ELSE '' 
        END AS DESC_TECNOLOGIA,
		ID_DEPARTAMENTO,
		REPLACE(DESC_DEPARTAMENTO, '+ü', 'A') AS DESC_DEPARTAMENTO,
		ID_MUNICIPIO,
		CASE 
            WHEN ID_MUNICIPIO = 11001 THEN 'Bogota'
            WHEN ID_MUNICIPIO = 76001 THEN 'Cali'
			WHEN ID_MUNICIPIO = 5001  THEN 'Medellin'
            WHEN ID_MUNICIPIO = 8001  THEN 'Barranquilla'
            ELSE '' 
        END AS DESC_MUNICIPIO,
		ID_DIVISION_ADMINISTRATIVA,DESC_DIVISION_ADMINISTRATIVA,
		TIEMPO_TOTAL_INDISPONIBILIDAD,
		REPLACE(PORCENTAJE_DE_DISPONIBILIDAD, ',', '.') AS PORCENTAJE_DE_DISPONIBILIDAD,TRANSMISION_SATELITAL
    FROM Ind_Disp_Red_Acceso 
    WHERE
        (id_empresa IN (800153993, 830114921, 830122566, 901354361, 805006014)) AND
        (id_MUNICIPIO IN (11001, 5001, 76001, 8001))
)
SELECT PORCENTAJE_DE_DISPONIBILIDAD,count(porcentaje_de_disponibilidad) FROM TBL
group by PORCENTAJE_DE_DISPONIBILIDAD order by PORCENTAJE_DE_DISPONIBILIDAD asc ;