Drop table Ind_Disp_Red_Acceso;
CREATE TABLE Ind_Disp_Red_Acceso (
    ANNO INT,
    MES INT,
    ID_EMPRESA BIGINT,
    DESC_EMPRESA VARCHAR(100),
    ID_ELEMENTO INT,
    ELEMENTO_PACTADO VARCHAR(1),  
    ID_TECNOLOGIA INT,
    DESC_TECNOLOGIA VARCHAR(100),
    ID_DEPARTAMENTO INT,
    DESC_DEPARTAMENTO VARCHAR(100),
    ID_MUNICIPIO INT,
    DESC_MUNICIPIO VARCHAR(100),
    ID_DIVISION_ADMINISTRATIVA INT,
    DESC_DIVISION_ADMINISTRATIVA VARCHAR(100),
    ID_ZONA INT,
    TIEMPO_TOTAL_INDISPONIBILIDAD FLOAT,
    PORCENTAJE_DE_DISPONIBILIDAD FLOAT,
    TRANSMISION_SATELITAL VARCHAR(1)
);

BULK INSERT Ind_Disp_Red_Acceso
FROM 'D:\Drive\Tesis ,  IG Teleco\Base de datos\F2_7_DISP_ELEMENTO_RED_ACCESO_12.csv'  
WITH (
    FIELDTERMINATOR = ';',  
    ROWTERMINATOR = '\n',  
    FIRSTROW = 2  
);


