Drop table Ind_Disp_Red_Acceso_Filtro;
CREATE TABLE Ind_Disp_Red_Acceso_Filtro (
    ANNO INT,
    MES INT,
    ID_EMPRESA BIGINT,
    ID_TECNOLOGIA INT,
    ID_MUNICIPIO INT,
    TIEMPO_TOTAL_INDISPONIBILIDAD FLOAT,
    PORCENTAJE_DE_DISPONIBILIDAD FLOAT

);


WITH TBL AS (
    SELECT 
        ANNO, MES, ID_EMPRESA, ID_TECNOLOGIA,
        ID_MUNICIPIO, TIEMPO_TOTAL_INDISPONIBILIDAD, PORCENTAJE_DE_DISPONIBILIDAD 
    FROM Ind_Disp_Red_Acceso 
    WHERE
        (id_empresa IN (800153993, 830114921, 830122566, 901354361, 830016046, 805006014)) AND
        (id_MUNICIPIO IN (11001, 5001, 76001, 8001))
)
INSERT INTO Ind_Disp_Red_Acceso_Filtro (ANNO, MES, ID_EMPRESA, ID_TECNOLOGIA, ID_MUNICIPIO, TIEMPO_TOTAL_INDISPONIBILIDAD, PORCENTAJE_DE_DISPONIBILIDAD)
SELECT * FROM TBL
ORDER BY ANNO DESC, MES DESC, TIEMPO_TOTAL_INDISPONIBILIDAD;